name: Build and Deploy Frontend

on:
  push:
    branches:
      - main # 触发动作的分支，根据实际情况修改

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      # 使用GitHub Actions的 secrets 特性来安全存储PAT
      GH_PAT: ${{ secrets.SECRET_TOKEN }}

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies & Build
      run: |
        npm ci
        npm run build # 假设这是构建前端项目的npm脚本命令

    - name: Push to Another Repository With Token
      run: |
        git config --global url."https://${{ env.GH_PAT }}@github.com/".insteadOf https://github.com/
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git clone --branch main https://github.com/Lhk1008611/Lhk1008611.github.io.git dest
        cp -r build/* dest/ # 假设'build'是构建产物的输出目录
        cd dest
        git add .
        git commit -m "Automatically deploy from ${GITHUB_SHA} [skip ci]"
        git push

